elasticsearchPUBLICBASEURL: https://logs.online.olimpiada.ru/
elasticsearchHosts: http://elasticsearch-master.logging.svc:9200

serverHost: "0.0.0.0"

nodeSelector:
  node-role: monitoring

basicAuth:
  enabled: true

ingress:
  enabled: true
  apiVersion: "extensions/v1beta1"
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: logs.online.olimpiada.ru
      paths:
        - path: /
  tls:
    - secretName: letsencrypt-logs
      hosts:
        - logs.online.olimpiada.ru


