elasticsearchPUBLICBASEURL: https://logs.sirius.online/

resources:
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: monitoring

ingress:
  enabled: true
  apiVersion: "extensions/v1beta1"
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: logs.sirius.online
      paths:
        - path: /
