{{- if .Values.ingress.enabled -}}
{{- $fullName := "kibana" -}}
{{- $httpPort := .Values.httpPort -}}
{{- $pathtype := .Values.ingress.pathtype -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: {{ .Values.ingress.apiVersion | default "networking.k8s.io/v1" }}
kind: Ingress
metadata:
  name: kibana
  labels: {{ include "kibana.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- if .ingressPath }}
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- else }}
{{ toYaml .Values.ingress.tls | indent 2 }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    {{- if $ingressPath }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $ingressPath }}
        pathType: {{ $pathtype }}
        backend:
          {{- if $.Values.ingress.apiVersion }}
          serviceName: kibana
          servicePort: http
          {{- else }}
          service:
            name: kibana
            port:
              number: {{ $httpPort }}
          {{- end }}
    {{- else }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ $pathtype }}
        backend:
          {{- if $.Values.ingress.apiVersion }}
          serviceName: kibana
          servicePort: http
          {{- else }}
          service:
            name: kibana
            port:
              number: {{ $httpPort }}
          {{- end }}
      {{- end }}
    {{- end }}
 {{- end }}
{{- end }}
