stages:
  - cpm
  - corp
  - univ
  - sirius

.base-kibana:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
  script:
    - kubectl get ns kibana || kubectl create ns kibana
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="kibana"
      NAMESPACE="kibana"
      CHART="chart"
      HELM_ARGS="
      -f chart/conf/${CLUSTER_NAME}/values.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${INFRA_REGISTRY}"
      --set global.basic_auth="${CPM_BASIC_AUTH}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

#############  CPM-DEV  ############

cpm kibana stage:
  extends:
    - .base-kibana
  stage: cpm
  variables:
    CLUSTER_NAME: "cpm-dev"
  tags:
    - kube-cpm

#############  CPM-YC  ############

cpm kibana prod:
  extends:
    - .base-kibana
  stage: cpm
  variables:
    CLUSTER_NAME: "cpm"
  tags:
    - cpm-yac

#############  CORP  ############

corp kibana prod:
  extends:
    - .base-kibana
  stage: corp
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

#############  UNIV  ############

univ kibana prod:
  extends:
    - .base-kibana
  stage: univ
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

#############  SIRIUS  ############

sirius kibana prod:
  extends:
    - .base-kibana
  stage: sirius
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci
