elasticsearchPUBLICBASEURL: https://logs-corp.sirius.online

imagePullSecrets:
- name: infra-registry

ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: logs-corp.sirius.online
      paths:
        - path: /
    - host: logs-corp.internal.sirius.online
      paths:
        - path: /

nodeSelector:
  node-role: monitoring

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: monitoring

secrets:
  enabled: false