---
# Публичный адрес для kibana, должен быть перечислен и в ingress.hosts
elasticsearchPUBLICBASEURL: ""
# IP адрес хоста
elasticsearchHosts: http://elasticsearch-master.logging.svc:9200
# Внутренний DNS адрес (в локальном имени)
elasticsearchURL: ""
# Адрес, на котором сервер слушает коннекты 
serverHost: "0.0.0.0"

# Кол-во реплик
replicas: 1

# Информация об образе
#image: "cr.yandex/crpcm9tg75s8gu2hqkp9/kibana"
image: "registry.sirius.online/infra/kibana"
imageTag: "7.16.1"
imagePullPolicy: "IfNotPresent"

# Дополнительные ярлыки pod-а
labels: {}
# Аннотации для сервиса
annotations: {}
# Аннонтации для пода
podAnnotations: {}

# Ресурсы по умолчанию
resources:
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    cpu: "800m"
    memory: "2Gi"

# Внутренний протокол kibana
protocol: http

# Путь, по которому работают health проверки
healthCheckPath: "/app/kibana"

# Пользователь под которым работает kibana
podSecurityContext:
  fsGroup: 1000

# Настройки security
securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# 
automountToken: false

# Внутренний порт
httpPort: 5601

# Настройки обновления подов
updateStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate

# Настройки сервисов
service:
  type: ClusterIP
  port: 5601
  labels: {}
  annotations: {}
  httpPortName: http

# basic auth
basicAuth:
  enabled: false

# Включаем ли мы ingress-ы
ingress:
  enabled: false

# Сприкт для проверки живости пода
readinessProbe:
  exec:
    command:
    - bash
    - -c
    - |
      #!/usr/bin/env bash -e
      # Disable nss cache to avoid filling dentry cache when calling curl
      # This is required with Kibana Docker using nss < 3.52
      export NSS_SDB_USE_CACHE=no
      http () {
          local path="${1}"
          set -- -XGET -s --fail -L
          if [ -n "${ELASTICSEARCH_USERNAME}" ] && [ -n "${ELASTICSEARCH_PASSWORD}" ]; then
            set -- "$@" -u "${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}"
          fi
          STATUS=$(curl --output /dev/null --write-out "%{http_code}" -k "$@" "http://localhost:5601${path}")
          if [[ "${STATUS}" -eq 200 ]]; then
            exit 0
          fi
          echo "Error: Got HTTP code ${STATUS} but expected a 200"
          exit 1
      }
      http "/app/kibana"
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

# Настройки секретов
imagePullSecrets:
- name: sirius-registry
- name: gitlab-registry

# Каким образом мы выбираем ноду для запуска
nodeSelector:
  node-role: monitoring

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""
