affinity: {}
elasticsearchHosts: 'http://elasticsearch-master:9200'
elasticsearchURL: ''
extraEnvs: []
fullnameOverride: ''
healthCheckPath: /app/kibana
httpPort: 5601
image: docker.elastic.co/kibana/kibana
imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: 7.5.0
ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  path: /
  tls: []
kibanaConfig: {}
labels: {}
lifecycle: {}
maxUnavailable: 1
nameOverride: ''
nodeSelector:
  node-role: monitoring
podAnnotations: {}
podSecurityContext:
  fsGroup: 1000
priorityClassName: ''
protocol: http
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5
replicas: 1
resources:
  limits:
    cpu: 800m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 300Mi
secretMounts: []
securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
serverHost: 0.0.0.0
service:
  annotations: {}
  nodePort: ''
  port: 5601
  type: ClusterIP
serviceAccount: ''
tolerations:
  - effect: NoSchedule
    key: node-role
    operator: Equal
    value: monitoring
updateStrategy:
  type: Recreate
