elasticsearchPUBLICBASEURL: https://logs-univ.sirius.online

tolerations:
- effect: NoSchedule
  key: node-role
  operator: Equal
  value: monitoring

ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: logs-univ.sirius.online
      paths:
        - path: /
